### ISSUE TITLE
qbit.ninja return wrong data : Imp*

### ISSUE THREAD

**Issue by Ashish81** [MetacoSA/NBitcoin#324] opened 2017-12-20 16:04 UTC
Hi, Nicolas , A serious issue.

This url returns the coins which is already spent.
https://api.qbit.ninja/balances/1kc5rSP1ZsE43SL4M7UY4BDXTqab6YiVb?unspentonly=true

please see that the above returned coin is spent in below below txid
https://api.qbit.ninja/transactions/b635be9ebd960118b47359826fd41699b25260a227e5d8dc7bbefa26796130db .

**Comment by NicolasDorier** [comment] 2017-12-21 13:10
@Ashish81 so this is not an error per se.

The reason is that the transaction spending this coin is unconfirmed and QBitNinja "forget" the unconfirmed after 24H by default.

Because of the large mempool this happens quite a lot these days, so I released a new version of `QBitNinjaClient` package where you can use `QBitNinjaClient.UnconfirmedExpiration=9999999` so that it does not forget.
Checkout:

https://api.qbit.ninja/balances/1kc5rSP1ZsE43SL4M7UY4BDXTqab6YiVb?unspentonly=true&unconfExpiration=99999

**Comment by NicolasDorier** [comment] 2017-12-21 13:11
Closing this as this should solve your issue, please reopen if you need.

**Closed by NicolasDorier** 2017-12-21 13:11 UTC
