### ISSUE TITLE
SPV wallet (database integration)

### ISSUE THREAD

**Issue by ghost** [MetacoSA/NBitcoin#274] opened 2017-08-16 19:03 UTC
Hello,

is there a simple way to store public/private key pairs and address hashes not only as JSON but also in a database?
I want to store all the data which is currently stored as JSON in a database. JSON is not so appropiate when dealing with many bitcoin addresses.

Regards
Martin

**Comment by NicolasDorier** [comment] 2017-08-17 02:32
There is no way, but your can easily adapt my code to work on database. Just copy/paste the `TrackerBehavior` and `SPVWallet`, and use a DB instead of JSON file.

The problem is that SPV bloom filters are limited to a certain number of tracked address, because of the max size of the loaded bloom filter. (I think it is around 10 000)

Which mean, if you want to make your own address tracking service, the best is to download full blocks and scan tracked addresses from it.

This is exactly what I have done with this project https://github.com/Dgarage/ElementsExplorer except it is using Elements and not Bitcoin.

I will probably make a bitcoin version in near futrue, but meanwhile you can use it.

**Comment by maddin123** [comment] 2017-08-17 19:08
Hi,

so the bloom filters in bitcoin are system intrinsically limited, when i understood right?
You have coded a NBitcoin.Indexer. How about that?

Regards
Martin

**Comment by NicolasDorier** [comment] 2017-08-18 07:56
@maddin123 please wait 1 or 2 more days, I just created a new project to make it more easy. Will publish soon.

**Comment by maddin123** [comment] 2017-08-18 10:35
Thx!

**Comment by NicolasDorier** [comment] 2017-08-18 21:42
Ok so take a look at https://github.com/dgarage/NBXplorer . Note this is a relatively new project, I will provide things to make it more easy to use with NBitcoin soon. However you have all your need, namely, a ExplorerClient.Sync  which sends you the UTXOs from a HD pubkey.

Try it, if you find any issue on this, let me know in the issues tracker there.

**Comment by maddin123** [comment] 2017-08-19 18:09
Hello Nicolas,

have some probs! Pls see issue tracker @NBXplorer.
Problem: it does not work with neither TestNet not with Main net. Always get connection refused or not understood. I use the latest BicoinCore client.

NBitcoin with `Node.Connect(Network.TestNet, "127.0.0.1:18333")` works!

Regards
Martin

**Comment by NicolasDorier** [comment] 2017-08-23 10:14
Can you try again ?

**Comment by NicolasDorier** [comment] 2017-08-23 10:14
git pull before trying, don't forget to run `dotnet run -testnet`

**Comment by NicolasDorier** [comment] 2017-12-10 06:56
Closing, redirected https://github.com/dgarage/NBXplorer/issues/1

**Closed by NicolasDorier** 2017-12-10 06:56 UTC
