### ISSUE TITLE
Litecoin RPC `GetBlock()` throws `System.FormatException: Unknown Transaction optional data` for some blocks

### ISSUE THREAD

**Issue by rvnlord** [MetacoSA/NBitcoin#1108] opened 2022-06-21 22:46 UTC
There is a bug with `Litecoin` serializer which will throw `System.FormatException: Unknown Transaction optional data` for some transactions in some blocks. To reproduce run:
```
var customHash = (await Rpc.GetBlockHeaderAsync(2284382)).GetHash();
var block = await Rpc.GetBlockAsync(customHash);
```
or
```
var resp = await Rpc.SendCommandAsync(RPCOperations.getblock, CancellationToken.None, customHash, false);
var block2 = Network.Main.Consensus.ConsensusFactory.CreateBlock();
var s = new BitcoinStream(new MemoryStream(Encoders.Hex.DecodeData(resp.ResultString)), false) { ConsensusFactory = Network.Main.Consensus.ConsensusFactory };
block2.ReadWrite(s);
```

Example transaction that causes the problem can be found in block `2284382` with `3bed06209f382e20f7b4eb1724366835874769763744d3cc429182422c8e7950` hash.

**Comment by NicolasDorier** [comment] 2022-06-22 07:12
@rvnlord can you copy the transaction's hex here?

**Comment by rvnlord** [comment] 2022-06-22 22:00
`02000000000801d0e493224859b9210af6f88791365b2d40fe45099feeff1474bbc69c5e9200060000000000ffffffff0112bab955d700000022582073a2485a7c127ffca4e0c39484a5145307ea86771f57b6a87be195a3813e3f2e0000000000`

**Comment by NicolasDorier** [comment] 2022-09-22 06:39
Should be fixed https://github.com/MetacoSA/NBitcoin/issues/1125 was caused by a hardfork of ltc

**Closed by NicolasDorier** 2022-09-22 06:39 UTC
